alchemy/views/clazz.py
import flask
from flask import g
from alchemy import db, models, auth_manager, file_input, file_output
from alchemy.reports import report_types, data_manager
import urllib
import os

bp_clazz = flask.Blueprint('clazz', __name__)

@bp_clazz.url_value_preprocessor
def url_value_preprocessor(endpoint, values):
    g.clazz = models.Clazz.query.get_or_404(values.pop('clazz_id'))
    g.student_paper_report_sections_string = 'OverviewSection,AdjacentGradesSection,ClazzSummarySection,CohortSummarySection,HighlightsSection,TagDetailsSection,QuestionDetailsSection'
    g.clazz_paper_report_sections_string = 'OverviewSection,OverviewPlotSection,OverviewDetailsSection,GradeOverviewSection,TagOverviewSection,QuestionOverviewSection,TagDetailsSection,QuestionDetailsSection'
    g.clazz_checkpoint_report_sections_string = 'OverviewSection,GradeOverviewSection,OverviewDetailsSection,TagOverviewSection'

@bp_clazz.url_defaults
def url_defaults(endpoint, values):
    if 'clazz_id' not in values:
        values['clazz_id'] = g.clazz.id

@bp_clazz.before_request
def before_request():
    g.html_title = f'Class - {g.clazz.code}'

@bp_clazz.route('/')
@auth_manager.require_group
def index():
    # for paper in g.course.papers:
    #     paper.check_clazz_scores(g.clazz)
    student_course_profiles = data_manager.make_student_course_profiles(g.course, g.clazz.students)
    return flask.render_template('course/clazz/index.html', profiles = student_course_profiles)

@bp_clazz.route('view_reports')
@auth_manager.require_group
def view_reports():
    return flask.render_template('course/clazz/view_reports.html')

@bp_clazz.route('/student_scores_update', methods=['POST'])
@auth_manager.require_group
def student_scores_update():
    update_data = flask.request.get_json()
    paper_id = update_data['paper_id']
    student_scores = update_data['student_scores']
    modified_students = update_data['modified_students']

    # Expected columns are:
    # student id, given name, family name, [question 1, question 2, ...], total raw, total percent, grade

    if len(modified_students) == 0:
        print('No student scores were modified')
        return {}
    paper = models.Paper.query.get_or_404(paper_id)

    question_col_start = 3
    for score_row in student_scores:
        question_col_end = len(score_row) - 3
        student_id, given_name, family_name = score_row[:question_col_start]
        if str(student_id) not in modified_students:
            continue
        question_cols = score_row[question_col_start:question_col_end]
        total_raw, total_percent, grade = score_row[question_col_end:]
        if len(question_cols) != len(paper.paper_questions):
            print('Error! Received', len(question_cols), 'question columns for student', student_id, 'but found', len(paper.paper_questions), 'questions for paper', paper_id, 'in database')
            continue
        for i, paper_question in enumerate(paper.paper_questions):
            new_value = question_cols[i]
            if type(new_value) == 'str' and new_value.strip() == '':
                new_value = None    # clear the score value
            else:
                try:
                    new_value = float(question_cols[i])
                except ValueError:
                    print('Bad score value:', question_cols[i])
                    continue
            score = models.Score.query.filter_by(paper_id = paper_id, student_id = student_id, question_id = paper_question.question_id).first()
            if score:
                score.value = new_value
            else:
                score = models.Score(paper_id = paper_id, question_id = paper_question.question_id, student_id = student_id, value = new_value)
                db.session.add(score)
    db.session.commit()
    clazz_paper_profile = data_manager.ClazzPaperProfile(g.clazz, paper)
    # Make an array of the complete table data to be shown in the HTML table,
    # i.e. in the same format as the student_scores array that was received.
    tally_list_array = []
    for tally in clazz_paper_profile.paper_score_tallies:
        # add student id and name
        tally_list = [tally.student.id, tally.student.aws_user.given_name, tally.student.aws_user.family_name]
        # add values for all questions, or an empty string if there is no score
        tally_list.extend([score.value if score else '' for score in tally.scores])
        # add other tally details
        tally_list.extend([tally.raw_total, tally.percent_total, tally.grade])
        tally_list_array.append(tally_list)
    # Return the table data in JSON form
    return flask.jsonify(scores_table_json = tally_list_array)

@bp_clazz.route('/paper_results')
@auth_manager.require_group
def paper_results():
    paper = models.Paper.query.get_or_404(flask.request.args.get('paper_id'))
    clazz_paper_profile = data_manager.ClazzPaperProfile(g.clazz, paper)
    return flask.render_template('course/clazz/paper_results.html', clazz_paper_profile = clazz_paper_profile)

@bp_clazz.route('/mc_results_input')
@auth_manager.require_group
def mc_results_input():
    clazz = models.Clazz.query.get_or_404(flask.request.args.get('clazz_id'))
    paper = models.Paper.query.get_or_404(flask.request.args.get('paper_id'))
    student = models.Student.query.get_or_404(flask.request.args.get('student_id'))

    mc_input_macro = '''
          {% import "course/clazz/student_mc_input_macro.html" as mc_input %}
          {{ mc_input.render_mc_results(clazz, paper, student) }}
    '''

    return flask.jsonify(mc_input_html = flask.render_template_string(mc_input_macro, clazz = clazz, paper = paper, student = student))

@bp_clazz.route('/paper_report/<int:paper_id>/')
@auth_manager.require_group
def paper_report(paper_id):
    paper = models.Paper.query.get_or_404(paper_id)
    section_selection_string = flask.request.args.get('section_selection_string_get')
    section_selections = section_selection_string.split(',')
    clazz_report = report_types.ClazzPaperReport(g.clazz, paper, section_selections)
    return flask.render_template('course/clazz/paper_report.html', clazz_report = clazz_report)

@bp_clazz.route('/checkpoint_report/<int:checkpoint_id>/')
@auth_manager.require_group
def checkpoint_report(checkpoint_id):
    checkpoint = models.Checkpoint.query.get_or_404(checkpoint_id)
    section_selection_string = flask.request.args.get('section_selection_string_get')
    section_selections = section_selection_string.split(',')
    checkpoint_report = report_types.ClazzCheckpointReport(g.clazz, checkpoint, section_selections)
    return flask.render_template('course/clazz/checkpoint_report.html', checkpoint_report = checkpoint_report)

@bp_clazz.route('/mc_result_input_submit', methods=['POST'])
@auth_manager.require_group
def mc_result_input_submit():
    post_data = flask.request.get_json()
    clazz_id = post_data['clazz_id']
    paper_id = post_data['paper_id']
    student_id = post_data['student_id']
    mc_result_selection = post_data['mc_result_selection']

    for question_id, solution_id in mc_result_selection.items():
        question = models.Question.query.get_or_404(question_id)
        solution = models.Solution.query.get_or_404(solution_id)
        correct_solution = question.get_solution()
        if not correct_solution:
            print(f'No solution found for question {question_id}')
            continue

        # Update the score for this question on this paper
        score = models.Score.query.filter_by(paper_id = paper_id, question_id = question.id, student_id = student_id).first()
        if not score:
            score = models.Score(value = question.points, paper_id = paper_id, question_id = question.id, student_id = student_id)
            db.session.add(score)
        if correct_solution.id == solution.id:
            score.value = question.points
        else:
            score.value = 0
        score.selected_solution_id = solution.id

    db.session.commit()
    return flask.redirect(flask.url_for('course.clazz.paper_results', paper_id = paper_id))

alchemy/views/course.py
import flask
from flask import g
from alchemy import db, models, auth_manager

bp_course = flask.Blueprint('course', __name__)

@bp_course.url_value_preprocessor
def url_value_preprocessor(endpoint, values):
    g.course = models.Course.query.get_or_404(values.pop('course_id'))
    g.department = models.Department.query.get_or_404(g.course.department_id)
    g.school = models.School.query.get_or_404(g.department.school_id)

@bp_course.url_defaults
def url_defaults(endpoint, values):
    if 'course_id' not in values:
        values['course_id'] = g.course.id

@bp_course.before_request
def before_request():
    # only set title if not already set in a blueprint child
    if 'html_title' not in g:
        g.html_title = f'Course - {g.course.name}'

@bp_course.route('/')
@auth_manager.require_group
def index():
    g.course.order_grade_levels()
    return flask.render_template('course/index.html')

@bp_course.route('/edit_grade_levels', methods=['POST'])
@auth_manager.require_group
def edit_grade_levels():
    post_data = flask.request.get_json()
    course_id = post_data['course_id']
    grade_level_list = post_data['grade_levels']
    course = models.Course.query.get_or_404(course_id)
    if course.grade_levels:
        for g in course.grade_levels:
            db.session.delete(g)

    for i in range(len(grade_level_list)):
        if i == 0:
            upper_bound = 100
        elif i % 2 == 0:
            upper_bound = grade_level_list[i-1]
        else:
            continue
        new_grade = models.GradeLevel(grade = grade_level_list[i], lower_bound = grade_level_list[i+1], upper_bound = upper_bound, course_id = course.id)
        db.session.add(new_grade)

    db.session.commit()
    course.order_grade_levels()
    return flask.render_template('course/index.html')

@bp_course.route('/edit_categories', methods=['POST'])
@auth_manager.require_group
def edit_categories():
    post_data = flask.request.get_json()
    course_id = post_data['course_id']
    category_ids = post_data['category_ids']
    category_list = post_data['categories']
    course = models.Course.query.get_or_404(course_id)
    existing_ids = [category.id for category in course.assessment_categories]

    ## Delete unwanted categories ##
    for id in existing_ids:
        if id not in category_ids:
            category = models.AssessmentCategory.query.get_or_404(id)
            db.session.delete(category)

    ## Edit existing categories ##
    for i in range(len(category_list)):
        ## category_list contains (id, name, weight) for each category so every third element is a category id ##
        if i % 3 == 0:
            category_id = int(category_list[i])
            if category_id == 0:
                new_category = models.AssessmentCategory(name = category_list[i+1], weight = float(category_list[i+2]), course_id = course_id)
                db.session.add(new_category)
            else:
                for category in course.assessment_categories:
                    if category.id == category_id:
                        category.name = category_list[i+1]
                        category.weight = float(category_list[i+2])
    db.session.commit()
    course.order_assessment_categories()
    return flask.render_template('course/index.html')

@bp_course.route('/get_checkpoint_paper_ids/<int:checkpoint_id>', methods = ['GET'])
@auth_manager.require_group
def get_checkpoint_paper_ids(checkpoint_id):
    checkpoint = models.Checkpoint.query.get_or_404(checkpoint_id)
    checkpoint_paper_ids = []
    for paper in checkpoint.papers:
        checkpoint_paper_ids.append(paper.id)
    return flask.jsonify(paper_ids_json = checkpoint_paper_ids)

@bp_course.route('/edit_checkpoint/<int:checkpoint_id>', methods = ['POST'])
@auth_manager.require_group
def edit_checkpoint(checkpoint_id):
    post_data = flask.request.get_json()
    course_id = post_data['course_id']
    paper_ids = post_data['paper_ids']

    course = models.Course.query.get_or_404(course_id)
    checkpoint = models.Checkpoint.query.get_or_404(checkpoint_id)
    checkpoint.papers = []
    for paper_id in paper_ids:
        paper = models.Paper.query.get_or_404(paper_id)
        checkpoint.papers.append(paper)

    db.session.commit()
    return flask.render_template('course/index.html')

alchemy/views/student.py
import flask
from flask import g
import random
from alchemy import application, db, models, auth_manager
from alchemy.reports import data_manager, report_types

bp_student = flask.Blueprint('student', __name__)

@application.template_filter('shuffle')
def filter_shuffle(seq):
    try:
        result = list(seq)
        random.shuffle(result)
        return result
    except:
        return seq

@bp_student.url_value_preprocessor
def url_value_preprocessor(endpoint, values):
    g.student = models.Student.query.get_or_404(values.pop('student_id'))
    g.school = models.School.query.first()
    g.student_paper_report_sections_string = 'OverviewSection,AdjacentGradesSection,ClazzSummarySection,CohortSummarySection,HighlightsSection,TagDetailsSection,QuestionDetailsSection'
    g.student_checkpoint_report_sections_string = 'OverviewSection,AdjacentGradesSection,ClazzSummarySection,CohortSummarySection,HighlightsSection'

@bp_student.url_defaults
def url_defaults(endpoint, values):
    if 'student_id' not in values:
        values['student_id'] = g.student.id

@bp_student.route('/index')
@auth_manager.require_group
def index():
    return flask.render_template('student/index.html')

@bp_student.route('/courses')
@auth_manager.require_group
def courses():
    return flask.render_template('student/courses.html')


@bp_student.route('/course-view/<int:course_id>')
@auth_manager.require_group
def course_view(course_id):
    g.course = models.Course.query.filter_by(id = course_id).first()
    for clazz in g.student.clazzes:
        if clazz.course.id == g.course.id:
            g.clazz = clazz
    course_profile = data_manager.StudentCourseProfile(g.student, g.course)
    return flask.render_template('student/course_view.html', profile = course_profile)

@bp_student.route('/snapshots')
@auth_manager.require_group
def snapshots():
    return flask.render_template('student/snapshots.html')

@bp_student.route('/snapshots/<int:snapshot_id>/report')
@auth_manager.require_group
def snapshot_report(snapshot_id):
    snapshot = models.Snapshot.query.filter_by(id = snapshot_id).first()
    snapshot_report = report_types.SnapshotReport(g.student, snapshot)
    return flask.render_template('student/snapshot_report.html', snapshot_report = snapshot_report )

@bp_student.route('/student_paper_report/clazz/<int:clazz_id>/paper/<int:paper_id>')
@auth_manager.require_group
def paper_report(clazz_id=0, paper_id=0):
    paper = models.Paper.query.get_or_404(paper_id)
    clazz = models.Clazz.query.get_or_404(clazz_id)
    section_selection_string = flask.request.args.get('section_selection_string_get')
    section_selections = section_selection_string.split(',')
    student_report = report_types.StudentPaperReport(g.student, clazz, paper, section_selections)
    return flask.render_template('student/paper_report.html', student_report = student_report)

@bp_student.route('/student_paper_report/clazz/<int:clazz_id>/checkpoint/<int:checkpoint_id>')
@auth_manager.require_group
def checkpoint_report(clazz_id=0, checkpoint_id=0):
    checkpoint = models.Checkpoint.query.get_or_404(checkpoint_id)
    clazz = models.Clazz.query.get_or_404(clazz_id)
    section_selection_string = flask.request.args.get('section_selection_string_get')
    section_selections = section_selection_string.split(',')
    student_checkpoint_report = report_types.StudentCheckpointReport(g.student, clazz, checkpoint, section_selections)
    return flask.render_template('student/checkpoint_report.html', student_checkpoint_report = student_checkpoint_report)

alchemy/templates/course/clazz/index.html
{% extends "course/clazz/layout.html" %}

{% block clazz_tab_content %}

<main role="main">
  <h1 class="my-3">{{ g.clazz.code }} - {{ g.course.name }}</h1>

  <h2>Teacher</h2>
    <p style='margin-left:20px'>TEACHER! (eventually)</p>
  <!-- Eventually include a for teachers in clazz.teachers loop -->
  <h2>Students ({{ g.clazz.students | length }})</h2>
  <br>
  <table class="table table-hover">
    <thead>
      <th>Student ID</th>
      <th>Family Name, Given Name</th>
      {% for paper in g.course.papers %}
        <th>{{ paper.title }}</th>
      {% endfor %}
    </thead>
    {% for profile in profiles %}
      <tr>
        <td class="align-middle">{{ profile.student.id }}</td>
        <td class="align-middle"><a href ="{{ url_for('student.index', student_id = profile.student.id)}}">{{ profile.student.aws_user.family_name }}, {{ profile.student.aws_user.given_name }}</td>
        {% for paper_score_tally in profile.paper_score_tallies %}
          {% if paper_score_tally.has_all_scores() %}
            <td>{{ paper_score_tally.percent_total }}% | {{ paper_score_tally.grade }}  <br><a class="btn btn-success btn-sm" target="_blank" href="{{ url_for('student.paper_report', paper_id = paper_score_tally.paper.id, student_id = profile.student.id, clazz_id = g.clazz.id, section_selection_string_get = g.student_paper_report_sections_string ) }}" >View Report</a></td>
          {% else %}
            <td>No Grade Assigned<br><a class="btn btn-success btn-sm disabled">View Report</a>
            </td>
          {% endif %}
        {% endfor %}
      </tr>
    {% endfor %}
  </table>

</main>

{% endblock clazz_tab_content %}

alchemy/templates/course/clazz/layout.html
{% include "layout_start.html" %}

<script src="{{ url_for('static', filename='mc_results_input.js') }}"></script>

<div class="container">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link {{ 'active' if request.endpoint == 'course.clazz.index' }}" href="{{ url_for('course.clazz.index', clazz_id = g.clazz.id) }}">Home</a>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Results</a>
      <div class="dropdown-menu">
        {% for paper in g.course.papers %}
          <a class="nav-link {{ 'active' if request.endpoint == 'course.clazz.index' }}" href="{{ url_for('course.clazz.paper_results', paper_id = paper.id) }}">{{ paper.title }}</a>
        {% endfor %}
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link {{ 'active' if request.endpoint == 'course.clazz.view_reports' }}" href="{{ url_for('course.clazz.view_reports', clazz_id = g.clazz.id) }}">Reports</a>
    </li>
  </ul>
  <br>

  {% block clazz_tab_content %}
  {% endblock clazz_tab_content %}

</div>

{% include "layout_end.html" %}

alchemy/templates/course/clazz/paper_report.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% include "course/reports/layout_start.html" %}

<body>
  <h1 style="text-align:center">{{ clazz_report.title }}</h1>
  <h1 style="text-align:center">{{ clazz_report.subtitle }}</h1>
  <br>
  <div class='container'>

    {% for section in clazz_report.sections %}

    <div class='section'>
      {% import section.html_macro as section_html %}
      {{ section_html.render_section(section) }}
    </div>

    {% endfor %}

  </div>

</body>
{% include "layout_end.html" %}

</html>

alchemy/templates/course/clazz/paper_results.html
{% extends "course/clazz/layout.html" %}

{% block clazz_tab_content %}

<main role="main">
  <head>
    <meta charset="utf-8">
    <script src="https://bossanova.uk/jspreadsheet/v4/jexcel.js"></script>
    <link rel="stylesheet" href="https://bossanova.uk/jspreadsheet/v4/jexcel.css" type="text/css" />
    <script src="https://jsuites.net/v4/jsuites.js"></script>
    <link rel="stylesheet" href="https://jsuites.net/v4/jsuites.css" type="text/css" />
    <title></title>
  </head>
  <body>
    <br>
    <h3>Student Results: {{ clazz_paper_profile.paper.title }} ({{ g.clazz.code }})</h3>
    <br>
    {% if clazz_paper_profile.paper.paper_questions|length == 0 %}
      <h5 color='red'>There are no Questions included in this assessment.</h5>
    {% else %}
      {% if clazz_paper_profile.paper.has_mc_questions() %}
        <h4>Multiple Choice Questions</h4>
        <br>
        <p>Record the results for multiple choice questions using the 'Edit' button for each student instead of entering the individual number of points of each question. The inputted results will be marked automatically and recorded below.</p>
        <br>
        <table class="table table-sm table-hover">
          <thead>
            <tr>
              <th>Student ID</th>
              <th>Given Name</th>
              <th>Family Name</th>
              <th>Edit results</th>
              <th>All results recorded?</th>
            </tr>
          </thead>
          {% for student in g.clazz.students %}
            <tr>
              <td class="align-middle">{{ student.id }}</td>
              <td class="align-middle">{{ student.aws_user.given_name }}</td>
              <td class="align-middle">{{ student.aws_user.family_name }}</td>
              <td class="align-middle">
                <a role="button"
                    aria-label="Edit question"
                    onclick="mc_results_form_load({{ g.clazz.course.id }}, {{ g.clazz.id }}, {{ clazz_paper_profile.paper.id }}, {{ student.id }})"
                    class="btn btn-link">
                  <span data-feather="edit"></span>
                </a>
              <td class="align-middle">{{ 'Yes' if student.has_results_for_all_mc_questions(clazz_paper_profile.paper) else '--' }}</td>
            </tr>
          {% endfor %}
        </table>
      {% endif %}
      <div id="mc_input_area">
        <!-- mc input form injected here -->
      </div>
      <br>
      <h4>All Question Results</h4>
      <br>

      <table id="results_spreadsheet">
        <thead>
          <tr>
            <td>ID</td>
            <td>Given Name</td>
            <td>Family Name</td>
            {% for paper_question in clazz_paper_profile.paper.paper_questions %}
              <td>Question {{ paper_question.order_number }}
                ( / {{ paper_question.question.points | prettify_number }} )
              </td>
            {% endfor %}
            <td>Total (Raw)
              ( / {{ clazz_paper_profile.paper.profile.total_points | prettify_number }} )
            </td>
            <td>Total (%)</td>
            <td>Grade</td>
          </tr>
        </thead>

        <tbody>
          {% for tally in clazz_paper_profile.paper_score_tallies %}
          <tr>
          <td>{{ tally.student.id }}</td>
          <td>{{ tally.student.aws_user.given_name }}</td>
          <td>{{ tally.student.aws_user.family_name }}</td>
          {% for score in tally.scores %}
            <td>{{ score.value | prettify_number }}</td>
          {% endfor %}
          <td>{{ tally.raw_total | prettify_number }}</td>
          <td>{{ tally.percent_total | prettify_number }}</td>
          <td>{{ tally.grade }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <br>
      <p style="text-align: center;">
        <input id="save_scores_button" class="btn btn-primary btn-lg btn-block" type="button" value="Save Results" onclick="update_student_data()" disabled>
      </p>
      <br>
    {% endif %}
  </body>
</main>
<script type="text/javascript">
  let modified_students = {}
  let results_table = jexcel(document.getElementById('results_spreadsheet'), {
    lazyLoading: true,
    loadingSpin: true,
    tableOverflow: true,
    onbeforechange: function(instance, cell, x, y, value) {
      if (isNaN(value) || value < 0 || value > find_max_score_for_column(x)) {
        // Clear the field if an invalid value is entered
        return ''
      }
    },
    onchange: function(instance, cell, x, y, value) {
      var row_data = results_table.getRowData(y);
      var student_id = row_data[0]
      modified_students[student_id] = true
      $('#save_scores_button').prop('disabled', false)
    },
    updateTable: function(instance, cell, x, y, source, value, id) {
      // Ideally the known readonly columns would not be hardcoded here
      if (x < 3 || x > get_results_table_column_count() - 4) {
          cell.classList.add('readonly');
      }
    },
    contextMenu: function() {
        return false;
    }
  });
  for (var col = 0; col < get_results_table_column_count(); col++){
    results_table.setWidth(col, (col == 1 || col == 2) ? 150 : 100)
  }

  let max_scores = []
  {% for paper_question in clazz_paper_profile.paper.paper_questions %}
    max_scores.push( {{ paper_question.question.points }} )
  {% endfor %}

  function get_results_table_column_count() {
    return {{ clazz_paper_profile.paper.paper_questions | count }} + 6
  }

  function find_max_score_for_column(column) {
      var question_index = column - 3   // skip first three columns
      if (question_index < 0 || question_index > max_scores.length) {
        console.warn('Invalid question_index', question_index, 'for max_scores', max_scores)
        return 0
      }
      return max_scores[question_index]
  }

  function update_student_data() {
    scores_update({{ clazz_paper_profile.paper.id }}, results_table.getData(), modified_students )
    modified_students = {}
    $('#save_scores_button').prop('disabled', true)
  }

  function scores_update(paper_id, scores_json, modified_students) {
    $.ajax({
      type: 'POST',
      url: '{{ url_for('course.clazz.student_scores_update') }}',
      data: JSON.stringify({
        'paper_id': paper_id,
        'student_scores': scores_json,
        'modified_students': modified_students,
      }),
      contentType: 'application/json',
      dataType: 'json',
    }).done(function(data) {
      if (data) {
        results_table.setData(data.scores_table_json)
      }
    });
  }

  function mc_results_form_load(course_id, clazz_id, paper_id, student_id) {
    $.getJSON('/course/' + course_id + '/clazz/' + clazz_id + '/mc_results_input', {
      clazz_id: clazz_id,
      paper_id: paper_id,
      student_id: student_id
    }, function(data) {
      $('#mc_input_area').html(data.mc_input_html)
      mc_result_input_reload()
      $('#input_mc_modal').modal('show')
      init_page()
    })
  }

</script>

{% endblock clazz_tab_content %}

alchemy/templates/course/clazz/student_mc_input_macro.html
<!-- Input MC Modal -->

{% macro render_mc_results(clazz, paper, student) -%}
<form>
  <div class="modal fade" id="input_mc_modal" tabindex="-1" aria-labelledby="input_mc_modal_label" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="input_mc_modal_label">{{ student.aws_user.family_name }}, {{ student.aws_user.given_name }}: Multiple Choice</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Click on the student's selections for each question, then click 'Save' to record the results. Correct answers are shown in green.</p>
        <table id="mc_result_selection_table" class="table table-hover">
          <tr>
            <th class="align-middle text-center" width="5%">Question</th>
            <th class="align-middle text-center" width="50%"></th>
            <th class="align-middle text-center">Options</th>
          </tr>
          {% for paper_question in paper.get_mc_paper_questions() %}
            <tr>
              <td class="align-middle text-center">{{ paper_question.order_number }}</td>
              <td class="align-middle">{{ paper_question.question.content[0:64] }}...</td>
              <td class="align-middle text-center">
                {% for solution in paper_question.question.all_solutions %}
                  {% set is_selected_solution = (solution.id == paper_question.selected_solution_id(student.id)) %}
                  {% set is_correct_solution = (solution == paper_question.question.get_solution()) %}
                  <button
                        type="button"
                        class="btn {{ 'btn-success' if is_correct_solution else 'btn-light' }}"
                        style="border: solid 5px {{ 'orange' if is_selected_solution else 'transparent' }}"
                        onclick="mc_result_input_select($(this))"
                        data-alchemy_mc_question_id="{{ paper_question.question_id }}"
                        data-alchemy_mc_solution_id="{{ solution.id }}"
                        data-alchemy_mc_solution_correct="{{ is_correct_solution }}">
                    {{ paper_question.question.get_solution_label(solution) }}
                  </button>
                {% endfor %}
                &nbsp;
                <span style="visibility: {{ 'visible' if paper_question.selected_solution_id(student.id) == paper_question.question.get_solution().id else 'hidden' }}; color: green;"
                    id="mc_result_input_tick_{{ paper_question.question_id }}"
                    data-feather="check-circle"></span>
              </td>
            </tr>
          {% endfor %}
        </table>
      </div>
      <div class="modal-footer">
          <button
              id="mc_result_input_cancel"
              type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <button
              id="mc_result_input_save"
              class="btn btn-primary"
              onclick='mc_result_input_submit({{ clazz.course_id }}, {{ clazz.id }}, {{ paper.id }}, {{ student.id }})'>Save Changes</button>

      </div>
    </div>
  </div>
</form>
{%- endmacro %}