alchemy/views/course.py
import flask
from flask import g
from alchemy import db, models, auth_manager

bp_course = flask.Blueprint('course', __name__)

@bp_course.url_value_preprocessor
def url_value_preprocessor(endpoint, values):
    g.course = models.Course.query.get_or_404(values.pop('course_id'))
    g.department = models.Department.query.get_or_404(g.course.department_id)
    g.school = models.School.query.get_or_404(g.department.school_id)

@bp_course.url_defaults
def url_defaults(endpoint, values):
    if 'course_id' not in values:
        values['course_id'] = g.course.id

@bp_course.before_request
def before_request():
    # only set title if not already set in a blueprint child
    if 'html_title' not in g:
        g.html_title = f'Course - {g.course.name}'

@bp_course.route('/')
@auth_manager.require_group
def index():
    g.course.order_grade_levels()
    return flask.render_template('course/index.html')

@bp_course.route('/edit_grade_levels', methods=['POST'])
@auth_manager.require_group
def edit_grade_levels():
    post_data = flask.request.get_json()
    course_id = post_data['course_id']
    grade_level_list = post_data['grade_levels']
    course = models.Course.query.get_or_404(course_id)
    if course.grade_levels:
        for g in course.grade_levels:
            db.session.delete(g)

    for i in range(len(grade_level_list)):
        if i == 0:
            upper_bound = 100
        elif i % 2 == 0:
            upper_bound = grade_level_list[i-1]
        else:
            continue
        new_grade = models.GradeLevel(grade = grade_level_list[i], lower_bound = grade_level_list[i+1], upper_bound = upper_bound, course_id = course.id)
        db.session.add(new_grade)

    db.session.commit()
    course.order_grade_levels()
    return flask.render_template('course/index.html')

@bp_course.route('/edit_categories', methods=['POST'])
@auth_manager.require_group
def edit_categories():
    post_data = flask.request.get_json()
    course_id = post_data['course_id']
    category_ids = post_data['category_ids']
    category_list = post_data['categories']
    course = models.Course.query.get_or_404(course_id)
    existing_ids = [category.id for category in course.assessment_categories]

    ## Delete unwanted categories ##
    for id in existing_ids:
        if id not in category_ids:
            category = models.AssessmentCategory.query.get_or_404(id)
            db.session.delete(category)

    ## Edit existing categories ##
    for i in range(len(category_list)):
        ## category_list contains (id, name, weight) for each category so every third element is a category id ##
        if i % 3 == 0:
            category_id = int(category_list[i])
            if category_id == 0:
                new_category = models.AssessmentCategory(name = category_list[i+1], weight = float(category_list[i+2]), course_id = course_id)
                db.session.add(new_category)
            else:
                for category in course.assessment_categories:
                    if category.id == category_id:
                        category.name = category_list[i+1]
                        category.weight = float(category_list[i+2])
    db.session.commit()
    course.order_assessment_categories()
    return flask.render_template('course/index.html')

@bp_course.route('/get_checkpoint_paper_ids/<int:checkpoint_id>', methods = ['GET'])
@auth_manager.require_group
def get_checkpoint_paper_ids(checkpoint_id):
    checkpoint = models.Checkpoint.query.get_or_404(checkpoint_id)
    checkpoint_paper_ids = []
    for paper in checkpoint.papers:
        checkpoint_paper_ids.append(paper.id)
    return flask.jsonify(paper_ids_json = checkpoint_paper_ids)

@bp_course.route('/edit_checkpoint/<int:checkpoint_id>', methods = ['POST'])
@auth_manager.require_group
def edit_checkpoint(checkpoint_id):
    post_data = flask.request.get_json()
    course_id = post_data['course_id']
    paper_ids = post_data['paper_ids']

    course = models.Course.query.get_or_404(course_id)
    checkpoint = models.Checkpoint.query.get_or_404(checkpoint_id)
    checkpoint.papers = []
    for paper_id in paper_ids:
        paper = models.Paper.query.get_or_404(paper_id)
        checkpoint.papers.append(paper)

    db.session.commit()
    return flask.render_template('course/index.html')

alchemy/views/snapshot.py
## Temporary place for designing the Snapshot functionality ##

## course will need a new attribute - checkpoints. This will be a 1-to-many relationship, as one course can have multiple checkpoints. They will also need a new method, as below:

def get_snapshots(self):
    snapshot_list = []
    for checkpoint in self.checkpoints:
        snapshot_list.append(checkpoint.snapshot)
    return(snapshot_list)

## Classes ##

## Checkpoints are specific to courses and will be looped through to generate Snapshot reports ##
class Checkpoint:
    def __init__(self, name, course, snapshot, paper_list):
        self.name = name
        self.course = course
        self.snapshot = snapshot
        self.papers = paper_list

    ## Before the reports are published, the papers included in a checkpoint can be edited by a Head of Department ##
    def edit_included_papers(self, paper_list):
        self.papers = []
        for paper in paper_list:
            self.papers.append(paper)

    ## Snapshot reports will all be published together, but teachers will not finish all their marking and data entry at the same time --> need an easy way for individual courses to signal their 'readiness' for publishing.
    def is_ready(self):
        for paper in self.papers:
            if not paper.has_all_scores():
                return False
            else:
                return True

## Snapshots are instantiated by school admin, not individual courses. ##
#Snapshot reports are like your typical report card - they contain a brief summary of the student achievement in each course they taking, and will contain links to the more detailed checkpoint reports for each course. ##
class Snapshot:
    def __init__(self, name, course_list):
        self.name = name
        self.courses = course_list
        self.checkpoints = []
        self.is_published = False

    def is_ready(self):
        if not self.checkpoints:
            return False
        else:
            for checkpoint in self.checkpoints:
                if not checkpoint.check_if_ready():
                    return False
                else:
                    return True

    def publish(self):
        if self.check_if_ready():
            self.is_published = True


## Endpoints ##

## These endpoints will be in snapshots.py, but accessed throughout the site ##

## will get called on school.index --> doesn't exist yet. But this function would only be accessible above the course or department level.
def new_snapshot(name, course_list):
    new_snapshot = Snapshot(name, course_list)
    ## Default course_list will be 'all', but there are situations where some courses publish snapshots and others don't. Want to keep this option open for future.
    for course in  new_snapshot.course_list:
        new_checkpoint = Checkpoint(new_snapshot.name, course, new_snapshot, [])
        course.checkpoints.append(new_checkpoint)
        new_snapshot.checkpoints.append(new_checkpoint)


## Called on clazz.index and cohort.index for admin, teachers, and students
def student_checkpoint_report(student, checkpoint):
    if checkpoint.is_ready():
        checkpoint_profile = make_checkpoint_profile(student, checkpoint)
        return flask.render_template('student_checkpoint_report', checkpoint_profile = checkpoint_profile)
    ## - checkpoint_profile contains all the detailed data needed for the checkpoint_report
    ## make_checkpoint_profile probably in reports.data_manager
    ## - Send checkpoint_profile to the HTML templates for student_checkpoint_report ##
    else:
        pass

## Called on clazz.index but only for admin and teachers
def clazz_checkpoint_report(clazz, checkpoint):
    if checkpoint.check_if_ready():
        student_checkpoint_profiles = []
        for student in clazz:
            checkpoint_profile = make_checkpoint_profile(student, checkpoint)
            student_checkpoint_profiles.append(checkpoint_profile)

        clazz_checkpoint_profile = make_group_checkpoint_profile(student_checkpoint_profiles)
        return flask.render_template('clazz_checkpoint_report', checkpoint_profiles = student_checkpoint_profiles)
    ## - Calculate all student_checkpoint_profiles
    ## - use these as inputs for clazz_checkpoint_profile (most likely)
    ## - send this objects to the HTML template for clazz_checkpoint_report ##
    else:
        pass

## Called on cohort.index, only for admin (maybe teachers)
def cohort_checkpoint_report(course, checkpoint):
    if checkpoint.check_if_ready():
        student_checkpoint_profiles = []
        for clazz in course.clazzes:
            for student in clazz.students:
                checkpoint_profile = make_checkpoint_profile(student, checkpoint)
                student_checkpoint_profiles.append(checkpoint_profile)

        cohort_checkpoint_profile = make_group_checkpoint_profile(student_checkpoint_profiles)
        return flask.render_template('cohort_checkpoint_report', checkpoint_profiles = student_checkpoint_profiles)
    ## - Calculate all student_checkpoint_profiles
    ## - use these as inputs for cohort_checkpoint_profile (most likely)
    ## - send this to the HTML template for cohort_checkpoint_report ##
    else:
        pass

## Called on student.index - for students, teachers, and admin
def student_snapshot_report(student, snapshot):
    if snapshot.check_if_ready():
        checkpoint_summary_list = []
        for clazz in student.clazzes:
            checkpoint_summary = make_checkpoint_summary(student, clazz.course, snapshot)
            checkpoint_summary_list.append(checkpoint_summary)
        return flask.render_template('student_snapshot_report', checkpoint_summaries = checkpoint_summary_list)
        ## - Requires 'student_checkpoint_summary', each of which would come from a course that the student is taking
        ## make_checkpoint_summary probably located in reports.data_manager
        ## - These summaries contain quantities like their average score and grade from that course ##
        ## - Send these data_objects to template for student_snapshot_report
    else:
        pass

## Sequence ##

## 1) School admin runs new_snapshot() through UI

## 2) It creates new checkpoints for all the courses in course_list. new_snapshot default is_published attribute is false --> this should prevent any access to the snapshot reports (for each student) or checkpoint reports (for students, clazzes, and cohorts).

## 3) Course-level admin assign papers to the checkpoint.papers attribute for each course. A Checkpoint's readiness to be included in a Snapshot will automatically signalled once all scores are uploaded from all clazzes in a course.

## 4) Once all checkpoints from all courses are ready, Snapshot.check_if_ready() will return true. After this point, Snapshot.publish() can be called to make all checkpoint reports and snapshot reports available for viewing.

alchemy/views/student.py
import flask
from flask import g
import random
from alchemy import application, db, models, auth_manager
from alchemy.reports import data_manager, report_types

bp_student = flask.Blueprint('student', __name__)

@application.template_filter('shuffle')
def filter_shuffle(seq):
    try:
        result = list(seq)
        random.shuffle(result)
        return result
    except:
        return seq

@bp_student.url_value_preprocessor
def url_value_preprocessor(endpoint, values):
    g.student = models.Student.query.get_or_404(values.pop('student_id'))
    g.school = models.School.query.first()
    g.student_paper_report_sections_string = 'OverviewSection,AdjacentGradesSection,ClazzSummarySection,CohortSummarySection,HighlightsSection,TagDetailsSection,QuestionDetailsSection'
    g.student_checkpoint_report_sections_string = 'OverviewSection,AdjacentGradesSection,ClazzSummarySection,CohortSummarySection,HighlightsSection'

@bp_student.url_defaults
def url_defaults(endpoint, values):
    if 'student_id' not in values:
        values['student_id'] = g.student.id

@bp_student.route('/index')
@auth_manager.require_group
def index():
    return flask.render_template('student/index.html')

@bp_student.route('/courses')
@auth_manager.require_group
def courses():
    return flask.render_template('student/courses.html')


@bp_student.route('/course-view/<int:course_id>')
@auth_manager.require_group
def course_view(course_id):
    g.course = models.Course.query.filter_by(id = course_id).first()
    for clazz in g.student.clazzes:
        if clazz.course.id == g.course.id:
            g.clazz = clazz
    course_profile = data_manager.StudentCourseProfile(g.student, g.course)
    return flask.render_template('student/course_view.html', profile = course_profile)

@bp_student.route('/snapshots')
@auth_manager.require_group
def snapshots():
    return flask.render_template('student/snapshots.html')

@bp_student.route('/snapshots/<int:snapshot_id>/report')
@auth_manager.require_group
def snapshot_report(snapshot_id):
    snapshot = models.Snapshot.query.filter_by(id = snapshot_id).first()
    snapshot_report = report_types.SnapshotReport(g.student, snapshot)
    return flask.render_template('student/snapshot_report.html', snapshot_report = snapshot_report )

@bp_student.route('/student_paper_report/clazz/<int:clazz_id>/paper/<int:paper_id>')
@auth_manager.require_group
def paper_report(clazz_id=0, paper_id=0):
    paper = models.Paper.query.get_or_404(paper_id)
    clazz = models.Clazz.query.get_or_404(clazz_id)
    section_selection_string = flask.request.args.get('section_selection_string_get')
    section_selections = section_selection_string.split(',')
    student_report = report_types.StudentPaperReport(g.student, clazz, paper, section_selections)
    return flask.render_template('student/paper_report.html', student_report = student_report)

@bp_student.route('/student_paper_report/clazz/<int:clazz_id>/checkpoint/<int:checkpoint_id>')
@auth_manager.require_group
def checkpoint_report(clazz_id=0, checkpoint_id=0):
    checkpoint = models.Checkpoint.query.get_or_404(checkpoint_id)
    clazz = models.Clazz.query.get_or_404(clazz_id)
    section_selection_string = flask.request.args.get('section_selection_string_get')
    section_selections = section_selection_string.split(',')
    student_checkpoint_report = report_types.StudentCheckpointReport(g.student, clazz, checkpoint, section_selections)
    return flask.render_template('student/checkpoint_report.html', student_checkpoint_report = student_checkpoint_report)

alchemy/templates/student/checkpoint_report.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% include "course/reports/layout_start.html" %}

<body>
  <h1 style="text-align:center">{{ student_checkpoint_report.title }}</h1>
  <h1 style="text-align:center">{{ student_checkpoint_report.subtitle }}</h1>

  <div class='container'>

    {% for section in student_checkpoint_report.sections %}

    <div class='section'>
      {% import section.html_macro as section_html %}
      {{ section_html.render_section(section) }}
    </div>

    {% endfor %}

  </div>

</body>
{% include "layout_end.html" %}

</html>

alchemy/templates/student/course_view.html
{% extends "student/layout.html" %}

{% block student_tab_content %}

<div class='container'>
  <h2>Your Profile: {{ g.clazz.course.name }} - {{ g.clazz.code }}</h2>
</div>

<div class='container'>
  <div class="accordion" id="daily-header">
    <div class="card">
      <div class="card-header" id="header-title">
        <h3 class="mb-0">
          <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#header-content" aria-expanded="true" aria-controls="header-content">
            <h4>Teacher Notices</h4>
          </button>
        </h3>
      </div>
      <div id="header-content" class="collapse show" aria-labelledby="header-content" data-parent="#daily-header">
        <div class="card-body">
          <p>A spot for teachers to post any important updates</p>
        </div>
      </div>
    </div>
  </div>
</div>
<br>

<div class='container'>
  <h4>Assessment Profile</h4>
  <br>
  <table style="text-align:center" class="table table-hover">
    <tr>
      <th>Assessment</th>
      <th>Category | Weighting</th>
      <th>Total Available Marks</th>
      <th>Achievement</th>
      <th>Report</th>
    </tr>
    <tbody>
      {% for tally in profile.paper_score_tallies %}
        {% if tally.paper.paper_questions|length == 0 %}
          <tr>
            <td>{{ tally.paper.title }}</td>
            <td>{{ tally.paper.category.name }} | {{ tally.paper.category.weight }}%</td>
            <td>{{ tally.paper.profile.total_points }}</td>
            <td><p style="color: orange;">Coming Soon</p></td>
            <td><a class="btn btn-success btn-sm disabled">Not Yet Available</a></td>
          </tr>
        {% else %}
          <tr>
            <td>{{ tally.paper.title }}</td>
            {% if tally.has_all_scores %}
              <td>{{ tally.paper.category.name }} | {{ tally.paper.category.weight }}%</td>
              <td>{{ tally.paper.profile.total_points }}</td>
              <td> {{ tally.raw_total }} | {{ tally.percent_total }}% | {{ tally.grade }} </td>
              <td><a class="btn btn-success btn-sm" target="_blank" href="{{ url_for('student.paper_report', student_id = g.student.id, paper_id = tally.paper.id, clazz_id = g.clazz.id, section_selection_string_get = g.student_paper_report_sections_string) }}" >View Report</a></td>
            {% else %}
              <td>No Grade Assigned</td>
              <td><a class="btn btn-success btn-sm disabled">Not Yet Available</a></td>
            {% endif %}
          </tr>
        {% endif %}
      {% endfor %}
    </tbody>
  </table>
</div>

<div class='container'>
  <h4>Reporting Events</h4>
  <br>
  {% if g.school.snapshots|length == 0 %}
    <h5 color='red'>There are no Reporting Events to view.</h5>
  {% else %}
    <table style="text-align:center" class="table table-hover">
      <tr>
        <th>Reporting Event</th>
        <th>Achievement</th>
        <th>Report</th>
      </tr>
      <tbody>
        {% for tally in profile.checkpoint_tallies  %}
          <tr>
            <td>{{ tally.checkpoint.snapshot.name }}</td>
            {% if not tally.checkpoint.snapshot.is_published %}
              <td>No Grade Assigned</td>
              <td><a class="btn btn-success btn-sm disabled">Report Unavailable</a></td>
            {% else %}
              <td>{{ tally.grade }} | {{ tally.percentage }}% </td>
              <td><a class="btn btn-success btn-sm" target="_blank" href="{{ url_for('student.checkpoint_report', student_id = g.student.id, checkpoint_id = tally.checkpoint.id, clazz_id = g.clazz.id, section_selection_string_get = g.student_checkpoint_report_sections_string) }}">View Report</a></td>
            {% endif %}
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endif %}
</div>

{% endblock student_tab_content %}

alchemy/templates/student/courses.html
{% extends "student/layout.html" %}

{% block student_tab_content %}

<div class="container">
  <h3>Your Courses:</h3>
	<div class="row">
		<div class="MultiCarousel" data-bs-wrap='true' data-items="1,3,4,5" data-slide="1" id="MultiCarousel"  data-interval="1000">
      <div class="MultiCarousel-inner">
        {% for clazz in g.student.clazzes %}
          <div class="item">
            <div class="card-body d-flex align-items-center justify-content-center">
              <a href="{{ url_for('student.course_view', course_id = clazz.course.id) }}" >
                <h5 class="card-title">{{ clazz.course.name }}</h5>
                <p class="card-text">{{ clazz.code }}</p>
              </a>
            </div>
          </div>
        {% endfor %}
      </div>
      <button class="btn btn-primary leftLst"><</button>
      <button class="btn btn-primary rightLst">></button>
        </div>
	</div>

{% endblock student_tab_content %}

alchemy/templates/student/index.html
{% extends "student/layout.html" %}

{% block student_tab_content %}

<div class='container'>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h2>Welcome back, {{ g.student.aws_user.given_name }}!</h2>
  </div>
</div>

<div class='container'>
  <div class="accordion" id="daily-header">
    <div class="card">
      <div class="card-header" id="header-title">
        <h3 class="mb-0">
          <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#header-content" aria-expanded="true" aria-controls="header-content">
            <h4>Quote of the Day</h4>
          </button>
        </h3>
      </div>
      <div id="header-content" class="collapse show" aria-labelledby="header-content" data-parent="#daily-header">
        <div class="card-body">
          <p>"My friends, love is better than anger. Hope is better than fear. Optimism is better than despair. So let us be loving, hopeful and optimistic. And we’ll change the world." - Jack Layton</p>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<div class='container'>
  <div id='daily-notices'>
    <div class="accordion" id="daily-notices">
      <div class="card">
        <div class="card-header" id="notices-head">
          <h3 class="mb-0">
            <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#notices-content" aria-expanded="true" aria-controls="notices-content">
              <h4>Daily Notices</h4>
            </button>
          </h3>
        </div>
        <div id="notices-content" class="collapse show" aria-labelledby="notices-head" data-parent="#daily-notices">
          <div class="card-body">
            <p> A bunch of important notices for students</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<br>

{% endblock student_tab_content %}

alchemy/templates/student/layout.html
{% include "layout_start.html" %}

<!-- course carousel -->
<!-- <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css"> -->
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='course_carousel.css') }}">
<script src="{{ url_for('static', filename='course_carousel.js') }}"></script>

<div class="container">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link {{ 'active' if request.endpoint == 'student.index' }}" href="{{ url_for('student.index', student_id=g.student.id) }}">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link {{ 'active' if request.endpoint == 'student.courses' }}" href="{{ url_for('student.courses', student_id=g.student.id) }}">Courses</a>
    </li>
    <li class="nav-item">
      <a class="nav-link {{ 'active' if request.endpoint == 'student.snapshots' }}" href="{{ url_for('student.snapshots', student_id=g.student.id) }}">Reporting</a>
    </li>
  </ul>
  <br>
  {% block student_tab_content %}
  {% endblock student_tab_content %}
</div>

{% include "layout_end.html" %}

alchemy/templates/student/paper_report.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% include "course/reports/layout_start.html" %}

<body>
  <h1 style="text-align:center">{{ student_report.title }}</h1>
  <h1 style="text-align:center">{{ student_report.subtitle }}</h1>

  <div class='container'>

    {% for section in student_report.sections %}

    <div class='section'>
      {% import section.html_macro as section_html %}
      {{ section_html.render_section(section) }}
    </div>

    {% endfor %}

  </div>

</body>
{% include "layout_end.html" %}

</html>

alchemy/templates/student/snapshot_report.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% include "course/reports/layout_start.html" %}

<body>
  <h1 style="text-align:center">{{ snapshot_report.title }}</h1>
  <h1 style="text-align:center">{{ snapshot_report.subtitle }}</h1>
  <br>
  <table class="table table-hover">
    <thead>
      <th>Course</th>
      <th>Your Achievement</th>
      <th>Cohort Average</th>
      <th>Detailed Report</th>
    </thead>
    {% for section in snapshot_report.checkpoint_sections %}
      <tr>
        <td>{{ section.course.name }}</td>
        <td>{{ section.tally.percent_total }}% | {{ section.tally.grade }}</td>
        <td>{{ section.cohort_tally.percent_mean }}% | {{ section.cohort_tally.mean_grade }} </td>
        <td><a class="btn btn-success btn-sm" target="_blank" href="{{ url_for('student.checkpoint_report', student_id = g.student.id, checkpoint_id = section.checkpoint.id, clazz_id = section.tally.clazz.id, section_selection_string_get = g.student_checkpoint_report_sections_string) }}">View Report</a></td>
      </tr>
    {% endfor %}
  </table>

</body>
{% include "layout_end.html" %}

</html>

alchemy/templates/student/snapshots.html
{% extends "student/layout.html" %}

{% block student_tab_content %}


  <h3>Reporting Events</h3>
  <br>
  {% if not g.school.snapshots %}
    <h5 color='red'>There are no Reports to view.</h5>
  {% else %}
    <table class="table table-hover">
      <thead>
        <th>Event</th>
        <th>Report</th>
      </thead>
      {% for snapshot in g.school.snapshots %}
        <tr>
          <td> {{ snapshot.name }}
          {% if snapshot.is_published %}
            <td><a class="btn btn-success btn-sm" target="_blank" href="{{ url_for('student.snapshot_report', student_id = g.student.id, snapshot_id = snapshot.id) }}" >View Report</a>
            </td>
          {% else %}
            <td><a class="btn btn-success btn-sm disabled">Report Unavailable</a></td>
          {% endif %}
        </tr>
      {% endfor %}
    </table>
  {% endif %}


{% endblock student_tab_content %}